### ISSUE TITLE
UI/UX

### ISSUE THREAD

**Issue by Jorgnavarro** [Jorgnavarro/Bolf-Project#25]

**Comment by Jorgnavarro** [comment]
Menú inicio

**Comment by Jorgnavarro** [comment]
Menu Pausa

**Comment by LuzBallesteros24** [comment]
**Asignaciones:**

- Menú Principal
- Menú de Créditos
- Menú de Opciones
- Menú de Guía de Juego
- Menú de Perder
- Menú de Controles
